#docker run --rm -it --mount type=bind,source=$(pwd)/,target=/usr/src/app -p 3000:3000 node:20.15.1 bash
services:
  ui_app_dev:
    build:
        context: ..
        dockerfile: .devcontainer/Dockerfile.dev
    container_name: admin-catalog-app-dev
    ports:
      - 3000:3000
    volumes:
      - ../:/app
